name: Deploy Laravel to Shared Hosting

on:
  push:
    branches:
      - main   # or the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4


      # 2. Install dependencies locally on Actions runner (optional)
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      # 3. Deploy via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/repositories
            git fetch --all
            git reset --hard origin/master

            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan cache:clear
